version: '3.8'

services:
  backend:
    build:
      context: app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: carbon_pred_backend

  frontend:
    build:
      context: app/frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: "http://localhost:8000" 
    ports:
      - "3000:3000"
    container_name: carbon_pred_frontend
    depends_on:
      - backend
