version: '3.8'
services:
  backend:
    build:
      context: app/backend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - 8000

  frontend:
    env_file:
      - app/frontend/.env
    build:
      context: app/frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    expose:
      - 3000